# Generated by Django 3.1.1 on 2023-03-13 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='is_all_members_post_allowed',
        ),
        migrations.RemoveField(
            model_name='space',
            name='is_only_moderators_post_allowed',
        ),
        migrations.AddField(
            model_name='space',
            name='granted_members',
            field=models.ManyToManyField(blank=True, related_name='granted_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='posting_permission',
            field=models.CharField(choices=[('all', 'Any member can post'), ('granted', 'Only granted members can post'), ('moderators', 'Only moderators can post')], default='all', max_length=47),
        ),
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
